/*
    This file is automatically generated. Don't edit it, all changes will be lost afer next generating
*/

#ifndef $INC_GUARD_H
#define $INC_GUARD_H

#include <string>

#include "fsa.h"
#include "messages.h"

$FSM_IMPL_INC

class $FSM_CLASS_NAME: public $FSM_PROTOTYPE {
public:
    $FSM_CLASS_NAME(FsmImpl* fi);
    std::vector<MessageType> acceptedMessages() const;
    const char * getName() const { return impl()->fsm_full_name(); }

// STATES:
$STATE_DECLS

private:
    std::unique_ptr<$FSM_CLASS_NAME_Impl> fsm_impl_guard;
    inline $FSM_CLASS_NAME_Impl* impl() const { fsm_impl_guard.get(); }

// STATE CHANGERS: 
$STATE_CHANGERS_DECLS

// STATE HANDLERS:
$STATE_HANDLERS_DECLS

$ON_STATE_CHANGED_HANDLER

    void setStateDescriptionMap();
};

#endif // $INC_GUARD_H
