/*
    This file is automatically generated. Don't edit it, all changes will be lost afer next generating
*/

$FSM_HDR_INC

namespace {
	//  const state_method STATE_ALIAS = (state_method)&FsmClassName::stateName;
	$STATE_ALIASES
}

$FSM_CLASS_NAME::$FSM_CLASS_NAME(FsmImpl* fi) {
    fsm_impl_guard.reset( ($FSM_CLASS_NAME_Impl)fi );
    curr_state = impl()->getInitialState();
}

$STATE_DEFINITIONS

void PassingController::setStateDescriptionMap() {
    // state_desc_map.emplace(STATE_NAME, "state_name");
    $STATE_DESC_MAP_CONTENT
}

std::vector<MessageType> PassingController::acceptedMessages() const {
    return {
    	$ACPTD_MSG_LIST
    };
}


