/*
    This file is automatically generated. Don't edit it, all changes will be lost afer next generating
*/

#include "messages.h"

void Message::set_docs(const TravelDocument * doc1, const TravelDocument * doc2) {
    if (nullptr != doc1) {
        document1.reset((TravelDocument *)doc1->copy().release());
    }

    if (nullptr != doc2) {
        document2.reset((TravelDocument *)doc2->copy().release());
    }
}

void Message::set_buffer(const unsigned char* ptr, size_t data_size, bool copy) {
    if (copy && 0 != data_size) {
        auto* nptr = new unsigned char[data_size];
        std::memcpy(nptr, ptr, data_size);
        ptr = nptr;
    }

    if ( 0 != data_size ) {
        buffer.reset(ptr, [](const unsigned char *p ) { delete[] p; });
    }

    buffer_sz = data_size;
}

