/*
	This file is automatically generated. Don't edit it, all changes will be lost afer next generating
*/

#ifndef MESSAGE_FACTORY_H
#define MESSAGE_FACTORY_H

#include <string>

#include "messages.h"

class MessageFactory {
public:
	// params - sequence of key=val pairs. Example: key1=val1,key2=val2,
	static MessageFactory* create(const std::string param_str);
	virtual Message make(MessageType mt) = 0;
};

#endif  // MESSAGE_FACTORY_H