/*
	This file is automatically generated. Don't edit it, all changes will be lost afer next generating
*/

#ifndef MESSAGE_DATA_H
#define MESSAGE_DATA_H

struct MessageData {

};

#endif  // MESSAGE_DATA_H
